# Working with CSV Files in Pandas

This notebook walks through the most common ways to **read**, **inspect**, and **write** CSV files using `pandas`. Each section adds one new `read_csv()` (or `to_csv()`) parameter, explains what it does and when you'd use it, and then shows it in action.

## 1. Import Libraries and Explore the Input Files

We start by importing `numpy` and `pandas`, then walk the Kaggle input directory to see which datasets are available. This is boilerplate that Kaggle notebooks generate automatically — it just lists every file under `/kaggle/input`.

In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv
/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/deliveries.csv

*(Re-importing `pandas` here is redundant since it was already imported above — harmless, but not necessary.)*

In [6]:
import pandas as pd

## 2. Listing Files in a Directory

Before reading a CSV, it's useful to confirm the exact file name and path with Python's built-in `os.listdir()`.

In [7]:
import os

folder_path = '/kaggle/input/datasets/muhammadzafranai/cars-data-from-dekho'
print(os.listdir(folder_path))

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/datasets/muhammadzafranai/cars-data-from-dekho'

## 3. Reading a CSV File — `pd.read_csv()`

`pd.read_csv()` is the main entry point for loading CSV data into a **DataFrame**. At its simplest, you just pass the file path.

In [20]:
import pandas as pd

# Replace 'your_file_name.csv' with the actual file name found in the folder
df = pd.read_csv('/kaggle/input/datasets/muhammadzafranai/cars-dataset/CAR DETAILS FROM CAR DEKHO.csv')

In [21]:
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

## 4. Custom Column Names — `names`

If a CSV has no header row (or you want to rename columns while reading), pass a list of column names with `names=`. You'd typically pair this with `header=None` so pandas doesn't treat the first data row as a header.

In [22]:
# df = pd.read_csv('/kaggle/input/datasets/muhammadzafranai/cars-data-from-dekho/CAR DETAILS FROM CAR DEKHO.csv',names = ['indexes','Car_Name','Year','Selling_Price',	'Present_Price',	'Kms_Driven',	'Fuel_Type',	'Seller_Type',	'Transmission',	'Owner'])
# df

## 5. Reading the Diabetes Dataset — `header` and `index_col`

Loading the dataset with its default settings first, so we have a baseline to compare against.

In [23]:
df1 =  pd.read_csv('/kaggle/input/datasets/muhammadzafranai/diabetes-data/diabetes_dataset.csv')

In [24]:
df1

,PatientID,Age,Gender,BMI,BloodPressure,Insulin,Glucose,DiabetesPedigreeFunction,Outcome
0,1,52,0,30.239636,149,113,115,0.312886,1
1,2,53,1,30.932781,71,39,104,0.389526,0
2,3,21,0,45.092714,161,67,151,1.205869,0
3,4,39,0,47.795530,101,165,184,0.595201,1
4,5,22,1,20.718108,160,158,116,0.974248,1
...,...,...,...,...,...,...,...,...,...
95,96,28,1,47.903244,164,55,90,0.470471,1
96,97,56,1,34.282756,121,242,74,1.254736,1
97,98,58,0,35.490390,152,206,161,1.378215,0
98,99,60,1,40.044859,85,159,130,0.224376,0
99,100,40,0,37.899312,138,215,91,0.907850,0

### Specifying `header=0` explicitly

`header=0` tells pandas the **first row (row 0)** contains the column names. This is actually the default, so the result looks the same here — but it's useful to set explicitly when a file has extra rows above the real header.

In [25]:
df1 =  pd.read_csv('/kaggle/input/datasets/muhammadzafranai/diabetes-data/diabetes_dataset.csv', header = 0)

In [26]:
df1

,PatientID,Age,Gender,BMI,BloodPressure,Insulin,Glucose,DiabetesPedigreeFunction,Outcome
0,1,52,0,30.239636,149,113,115,0.312886,1
1,2,53,1,30.932781,71,39,104,0.389526,0
2,3,21,0,45.092714,161,67,151,1.205869,0
3,4,39,0,47.795530,101,165,184,0.595201,1
4,5,22,1,20.718108,160,158,116,0.974248,1
...,...,...,...,...,...,...,...,...,...
95,96,28,1,47.903244,164,55,90,0.470471,1
96,97,56,1,34.282756,121,242,74,1.254736,1
97,98,58,0,35.490390,152,206,161,1.378215,0
98,99,60,1,40.044859,85,159,130,0.224376,0
99,100,40,0,37.899312,138,215,91,0.907850,0

### Using a Column as the Index — `index_col`

`index_col` lets you use one of the CSV's own columns (e.g. an ID column) as the DataFrame's row index, instead of pandas generating a default `0, 1, 2, ...` index.

In [28]:
df1 =  pd.read_csv('/kaggle/input/datasets/muhammadzafranai/diabetes-data/diabetes_dataset.csv', index_col = 'PatientID')

In [29]:
df1

,Age,Gender,BMI,BloodPressure,Insulin,Glucose,DiabetesPedigreeFunction,Outcome
PatientID,,,,,,,,
1,52,0,30.239636,149,113,115,0.312886,1
2,53,1,30.932781,71,39,104,0.389526,0
3,21,0,45.092714,161,67,151,1.205869,0
4,39,0,47.795530,101,165,184,0.595201,1
5,22,1,20.718108,160,158,116,0.974248,1
...,...,...,...,...,...,...,...,...
96,28,1,47.903244,164,55,90,0.470471,1
97,56,1,34.282756,121,242,74,1.254736,1
98,58,0,35.490390,152,206,161,1.378215,0
99,60,1,40.044859,85,159,130,0.224376,0
100,40,0,37.899312,138,215,91,0.907850,0

## 6. Selecting Specific Columns — `usecols`

When a file has many columns but you only need a few, `usecols` loads just those — which is also faster and uses less memory than loading everything and dropping columns afterward.

In [30]:
df1 =  pd.read_csv('/kaggle/input/datasets/muhammadzafranai/diabetes-data/diabetes_dataset.csv', usecols = ['Age','BMI','Outcome'])
df1

    Age        BMI  Outcome
0    52  30.239636        1
1    53  30.932781        0
2    21  45.092714        0
3    39  47.795530        1
4    22  20.718108        1
..  ...        ...      ...
95   28  47.903244        1
96   56  34.282756        1
97   58  35.490390        0
98   60  40.044859        0
99   40  37.899312        0

[100 rows x 3 columns]

## 7. Reading CSV Files from the Web / GitHub

`pd.read_csv()` also accepts a URL. This first cell queries the GitHub API for the user's repos — this needs the `requests` library, which the original cell used without importing it, so it's added here.

In [31]:
import requests

In [64]:
r = requests.get("https://api.github.com/users/MuhammadZafran33/repos")
for repo in r.json():
    print(repo["name"])

ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /users/MuhammadZafran33/repos (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7e0891a80260>: Failed to resolve 'api.github.com' ([Errno -3] Temporary failure in name resolution)"))

Pandas can read a CSV directly from a **raw** GitHub URL (the `raw.githubusercontent.com` link, not the regular `github.com` page link — the regular page is HTML, not the raw file).

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/MuhammadZafran33/Algorithm-Arsenal/main/Data%20Science%20Full%20Course%20By%20WsCube%20Tech/%20Machine%20Learning%20Course/%20Supervised%20Learning%20in%20ML/car%20data.csv"

df = pd.read_csv(url)
print(df.head())

A handy trick: if you only have the normal `github.com/.../blob/...` link, you can convert it into a raw link with a simple string replacement, as shown below.

In [ ]:
import pandas as pd

github_url = "https://github.com/MuhammadZafran33/Algorithm-Arsenal/blob/main/Data%20Science%20Full%20Course%20By%20WsCube%20Tech/%20Machine%20Learning%20Course/%20Supervised%20Learning%20in%20ML/car%20data.csv"

raw_url = github_url.replace("github.com", "raw.githubusercontent.com").replace("/blob/", "/")

df = pd.read_csv(raw_url)
print(df.head())

## 8. Skipping Rows and Limiting Rows — `skiprows` and `nrows`

- `skiprows` skips a given number of rows (or a list of specific row indices) from the top of the file before reading.
- `nrows` limits how many rows are read in total — useful for quickly previewing a huge file without loading all of it.

In [33]:
df3 = pd.read_csv('/kaggle/input/datasets/muhammadzafranai/diabetes-data/diabetes_dataset.csv', skiprows=[0,1])
df3

      2  53  1  30.932781204498376   71   39  104  0.38952609064144195  0
0     3  21  0           45.092714  161   67  151             1.205869  0
1     4  39  0           47.795530  101  165  184             0.595201  1
2     5  22  1           20.718108  160  158  116             0.974248  1
3     6  73  1           25.080940  153   71   79             1.308201  1
4     7  64  1           39.641021   93   53  125             1.756948  0
..  ...  .. ..                 ...  ...  ...  ...                  ... ..
93   96  28  1           47.903244  164   55   90             0.470471  1
94   97  56  1           34.282756  121  242   74             1.254736  1
95   98  58  0           35.490390  152  206  161             1.378215  0
96   99  60  1           40.044859   85  159  130             0.224376  0
97  100  40  0           37.899312  138  215   91             0.907850  0

[98 rows x 9 columns]

In [34]:
df3 = pd.read_csv('/kaggle/input/datasets/muhammadzafranai/diabetes-data/diabetes_dataset.csv', nrows=50)
df3

,PatientID,Age,Gender,BMI,BloodPressure,Insulin,Glucose,DiabetesPedigreeFunction,Outcome
0,1,52,0,30.239636,149,113,115,0.312886,1
1,2,53,1,30.932781,71,39,104,0.389526,0
2,3,21,0,45.092714,161,67,151,1.205869,0
3,4,39,0,47.795530,101,165,184,0.595201,1
4,5,22,1,20.718108,160,158,116,0.974248,1
5,6,73,1,25.080940,153,71,79,1.308201,1
6,7,64,1,39.641021,93,53,125,1.756948,0
7,8,46,1,29.797374,81,123,99,0.194349,1
8,9,52,0,26.506155,119,195,178,2.018585,1
9,10,26,0,27.801654,104,56,74,1.606961,1
10,11,52,0,28.660349,102,200,188,0.296222,0
11,12,75,0,45.233099,102,237,102,2.196589,0
12,13,24,0,22.803572,130,136,187,2.310094,0
13,14,75,0,40.830696,120,147,134,0.246587,0
14,15,31,1,35.913829,112,177,80,0.764506,0
15,16,76,0,27.840070,170,229,154,2.034883,0
16,17,79,1,31.723097,81,235,95,1.895823,0
17,18,37,1,26.570519,136,249,132,0.542850,0
18,19,58,0,37.762682,134,160,155,0.602438,1
19,20,44,1,21.070217,102,253,128,0.989133,1
20,21,25,0,18.663323,109,90,96,1.262855,0
21,22,72,1,38.278674,143,23,167,1.583811,0
22,23,54,0,24.619630,112,88,174,0.985393,1
23,24,26,1,20.734639,113,267,168,1.210083,0
24,25,42,0,30.998691,98,244,198,1.893930,0
25,26,31,0,20.099209,82,21,124,0.188040,0
26,27,68,0,46.428440,81,188,75,0.705849,1
27,28,36,0,19.369928,164,155,164,1.812039,1
28,29,53,0,36.734244,115,182,171,2.248496,1
29,30,29,1,32.311935,71,184,72,1.328026,1
30,31,79,1,39.668823,104,136,92,1.377072,1
31,32,26,1,28.836809,156,208,122,0.357213,0
32,33,36,0,23.383811,150,19,152,1.173790,1
33,34,49,1,49.427988,159,43,154,1.378281,0
34,35,23,0,44.926405,77,179,147,0.681929,0
35,36,40,0,45.602745,162,150,179,0.746184,1
36,37,79,1,26.382918,95,159,70,1.005482,1
37,38,56,1,19.723294,143,231,120,0.148171,0
38,39,39,0,28.052864,159,146,73,0.872990,0
39,40,46,1,35.418096,103,84,182,0.607475,0
40,41,23,0,28.789514,174,266,101,0.885994,1
41,42,39,0,44.577874,76,196,103,0.387429,1
42,43,40,0,27.053602,137,181,161,2.237265,1
43,44,52,0,48.905433,127,105,164,1.524622,1
44,45,27,0,32.903853,178,216,141,1.729846,1
45,46,72,1,45.023727,144,33,108,1.994011,0
46,47,61,1,24.622971,98,53,187,1.296261,1
47,48,53,0,31.457648,105,140,72,0.308609,0
48,49,60,0,40.534635,158,187,192,1.389056,0
49,50,59,1,22.858122,90,155,119,1.508419,0

## 9. Handling Bad / Malformed Lines — `on_bad_lines`

Real-world CSVs sometimes have rows with the wrong number of fields, which normally raises an error. `on_bad_lines='skip'` tells pandas to silently drop those rows instead of failing (`on_bad_lines='warn'` does the same but prints a warning for each one).

In [35]:
import pandas as pd

# 'skip' ignores the bad lines entirely. 
# You can also use 'warn' to skip them but print a warning for each one.
df = pd.read_csv('/kaggle/input/datasets/muhammadzafranai/diabetes-data/diabetes_dataset.csv', on_bad_lines='skip')

# Save the cleaned data to a new CSV
df.to_csv('cleaned_file.csv', index=False)

In [36]:
df  = pd.read_csv('cleaned_file.csv')
df

,PatientID,Age,Gender,BMI,BloodPressure,Insulin,Glucose,DiabetesPedigreeFunction,Outcome
0,1,52,0,30.239636,149,113,115,0.312886,1
1,2,53,1,30.932781,71,39,104,0.389526,0
2,3,21,0,45.092714,161,67,151,1.205869,0
3,4,39,0,47.795530,101,165,184,0.595201,1
4,5,22,1,20.718108,160,158,116,0.974248,1
...,...,...,...,...,...,...,...,...,...
95,96,28,1,47.903244,164,55,90,0.470471,1
96,97,56,1,34.282756,121,242,74,1.254736,1
97,98,58,0,35.490390,152,206,161,1.378215,0
98,99,60,1,40.044859,85,159,130,0.224376,0
99,100,40,0,37.899312,138,215,91,0.907850,0

## 10. Setting Column Data Types — `dtype`

By default pandas infers each column's type automatically. `dtype` lets you force specific columns to a specific type (e.g. reading a numeric column as `int` instead of `float`), which saves memory and avoids surprises later.

In [37]:
df3 = pd.read_csv('/kaggle/input/datasets/muhammadzafranai/diabetes-data/diabetes_dataset.csv', dtype={'BMI': int})
df3

ValueError: cannot safely convert passed user dtype of int64 for float64 dtyped data in column 3

## 11. Parsing Dates — `parse_dates`

By default, date columns are read in as plain text (`object` dtype). Passing `parse_dates=['column_name']` tells pandas to convert that column into proper `datetime64` values, which unlocks date-based operations like sorting, filtering by date range, and extracting year/month/day.

In [38]:
df = pd.read_csv('/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [39]:
df = pd.read_csv('/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv', parse_dates=['date']).info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   datetime64[ns]
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(1), object(15)
memory usage: 171.2+ KB

In [40]:
df = pd.read_csv('/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv', parse_dates=['date'])
df

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

## 12. Converters — Transforming Values While Reading

`converters` applies a custom function to every value in a column **as the file is read**, before it even becomes part of the DataFrame. Here, a `rename()` function is used to shorten a long team name to its abbreviation.

In [41]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return

In [42]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name  # <-- This tells Pandas to keep the original name

In [43]:
rename("Royal Challengers Bangalore")

'RCB'

### CONVERTORS

In [45]:
df4 = pd.read_csv('/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv', converters={'team1':rename})
df4

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

The same idea, applied to **multiple columns at once** by passing a dictionary that maps each column name to the same converter function:

In [46]:
df4 = pd.read_csv(
    '/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv', 
    converters={
        'team1': rename, 
        'team2': rename,
        'toss_winner': rename,
        'winner': rename
    }
)
df4

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,RCB,Kolkata Knight Riders,RCB,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,RCB,Mumbai Indians,bat,RCB,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

An alternative to `converters`: read the file normally first, then loop over the target columns and apply the function with `.apply()` afterward. This is often simpler to read, at the cost of a small amount of extra memory/time versus converting while reading.

In [47]:
# 1. Load the CSV normally
df4 = pd.read_csv('/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv')

# 2. List the columns you want to change
team_columns = ['team1', 'team2', 'toss_winner', 'winner']

# 3. Apply your rename function to all of them using a quick loop
for col in team_columns:
    df4[col] = df4[col].map(rename)
df4

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,RCB,Kolkata Knight Riders,RCB,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,RCB,Mumbai Indians,bat,RCB,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

## 13. Reading Large Files in Chunks — `chunksize`

For files too large to comfortably fit in memory, `chunksize` makes `read_csv()` return an **iterator** of DataFrames instead of one big DataFrame — each chunk has at most `chunksize` rows. You then process each chunk in a loop.

In [48]:
dfs = pd.read_csv('/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv', chunksize = 400)

In [49]:
for chunks in dfs:
    print(chunks.shape)

(400, 20)
(400, 20)
(295, 20)

## 14. Alternative: Manual Iteration with `iterator=True`

`iterator=True` is similar to `chunksize`, but instead of automatically looping through fixed-size chunks, it gives you a reader object you can pull chunks from **on demand** with `.get_chunk(n)` — useful when you don't want to process the whole file, or want variable chunk sizes.

In [50]:
reader = pd.read_csv(
    '/kaggle/input/datasets/patrickb1912/ipl-complete-dataset-20082020/matches.csv',
    iterator=True
)

first_100 = reader.get_chunk(100)   # pull the first 100 rows
print(first_100.shape)

next_50 = reader.get_chunk(50)      # pull the NEXT 50 rows, continuing from where we left off
print(next_50.shape)

(100, 20)
(50, 20)

## 15. Saving a DataFrame to CSV — `to_csv()`

Once you've cleaned or transformed a DataFrame, `to_csv()` writes it back out to disk. A few parameters worth knowing:
- `index=False` — don't write the DataFrame's row index as a column (usually what you want, otherwise you get an extra unnamed column when you re-read the file).
- `columns=[...]` — only write a subset of columns.
- `sep=` — use a delimiter other than a comma.

In [51]:
# Default: writes every column, including the index, as a new column
df1.to_csv('diabetes_export.csv')

# Recommended for most cases: drop the index column
df1.to_csv('diabetes_export_no_index.csv', index=False)

# Write only specific columns
df1.to_csv('diabetes_subset.csv', columns=['Age', 'BMI', 'Outcome'], index=False)

# Confirm it round-trips correctly
pd.read_csv('diabetes_export_no_index.csv').head()

   Age        BMI  Outcome
0   52  30.239636        1
1   53  30.932781        0
2   21  45.092714        0
3   39  47.795530        1
4   22  20.718108        1

## 16. Custom Delimiters — `sep` / `delimiter`

Not every "CSV" actually uses a comma. Files exported from some tools use semicolons, tabs, or pipes instead. `sep` (an alias `delimiter` also exists) tells pandas which character separates the fields.

*(The example below builds a tiny CSV in memory with `io.StringIO` so it runs without needing an external file — the same `sep=` argument works identically with a real file path.)*

In [52]:
from io import StringIO

raw_data = "name;age;city\nAli;22;Peshawar\nSara;25;Lahore\nUsman;28;Bannu"

df_semicolon = pd.read_csv(StringIO(raw_data), sep=';')
df_semicolon

    name  age      city
0    Ali   22  Peshawar
1   Sara   25    Lahore
2  Usman   28     Bannu

## 17. Handling Missing Values — `na_values`

Real-world CSVs mark missing data in inconsistent ways: `?`, `NA`, `-`, empty strings, `"N/A"`, etc. Pandas already recognizes some common ones automatically, but `na_values` lets you tell it about custom placeholders in your specific dataset so they get converted to proper `NaN` values instead of being read as text.

In [53]:
raw_data = "name,age,city\nAli,22,Peshawar\nSara,?,Lahore\nUsman,NA,-"

df_missing = pd.read_csv(StringIO(raw_data), na_values=['?', 'NA', '-'])
df_missing

    name   age      city
0    Ali  22.0  Peshawar
1   Sara   NaN    Lahore
2  Usman   NaN       NaN

In [54]:
# Count how many missing values ended up in each column
df_missing.isnull().sum()

name    0
age     2
city    1
dtype: int64

## 18. File Encoding — `encoding`

Pandas assumes UTF-8 by default. Files exported from Excel on Windows, or older systems, are sometimes saved in a different encoding (e.g. `'latin1'` / `'cp1252'`) — reading them without specifying `encoding` can raise a `UnicodeDecodeError` or silently produce garbled characters for accented letters.

In [55]:
from io import BytesIO

raw_bytes = "city,notes\ncafé,münchen\n".encode('latin1')

df_encoded = pd.read_csv(BytesIO(raw_bytes), encoding='latin1')
df_encoded

   city    notes
0  café  münchen

## 19. Skipping Comment Lines — `comment`

Some CSVs (especially ones generated by scientific tools) include comment/metadata lines starting with a character like `#`. `comment='#'` tells pandas to ignore any line starting with that character, rather than trying to parse it as data.

In [56]:
raw_data = (
    "# exported on 2026-08-31\n"
    "name,age\n"
    "Ali,22\n"
    "# next row is a duplicate for testing\n"
    "Sara,25\n"
)

df_comment = pd.read_csv(StringIO(raw_data), comment='#')
df_comment

   name  age
0   Ali   22
1  Sara   25

## 20. Reading Compressed CSV Files — `compression`

Pandas can read `.csv.gz`, `.zip`, `.bz2`, and `.xz` files directly, without manually decompressing them first. `compression='infer'` (the default) figures it out from the file extension; you can also set it explicitly.

In [57]:
import gzip

raw_csv_bytes = "name,age\nAli,22\nSara,25".encode('utf-8')
compressed = gzip.compress(raw_csv_bytes)

df_gz = pd.read_csv(BytesIO(compressed), compression='gzip')
df_gz

# With a real file on disk this is even simpler — pandas infers the compression from the extension:
# df = pd.read_csv('some_file.csv.gz')

   name  age
0   Ali   22
1  Sara   25

## 21. Quick Exploration Methods

After loading a CSV, these are usually the first methods you reach for to understand the data before doing anything else:

| Method | What it shows |
|---|---|
| `df.head(n)` | first `n` rows (default 5) |
| `df.tail(n)` | last `n` rows (default 5) |
| `df.shape` | `(rows, columns)` |
| `df.columns` | list of column names |
| `df.dtypes` | data type of each column |
| `df.info()` | dtypes + non-null counts + memory usage, all at once |
| `df.describe()` | count/mean/std/min/max/quartiles for numeric columns |
| `df.isnull().sum()` | count of missing values per column |

In [58]:
df1.head()

   Age        BMI  Outcome
0   52  30.239636        1
1   53  30.932781        0
2   21  45.092714        0
3   39  47.795530        1
4   22  20.718108        1

In [59]:
df1.tail(3)

    Age        BMI  Outcome
97   58  35.490390        0
98   60  40.044859        0
99   40  37.899312        0

In [60]:
print(df1.shape)
print(df1.columns)
print(df1.dtypes)

(100, 3)
Index(['Age', 'BMI', 'Outcome'], dtype='object')
Age          int64
BMI        float64
Outcome      int64
dtype: object

In [61]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Age      100 non-null    int64
 1   BMI      100 non-null    float64
 2   Outcome  100 non-null    int64
dtypes: float64(1), int64(2)
memory usage: 2.5 KB

In [62]:
df1.describe()

              Age         BMI  Outcome
count  100.000000  100.000000   100.00
mean    49.270000   32.452396     0.45
std     17.750718    9.357709     0.50
min     21.000000   18.663323     0.00
25%     36.000000   24.294953     0.00
50%     50.500000   31.260253     0.00
75%     62.500000   40.080581     1.00
max     79.000000   49.427988     1.00

In [63]:
df1.isnull().sum()

Age        0
BMI        0
Outcome    0
dtype: int64

## Summary — `read_csv()` Parameters Covered

| Parameter | Purpose |
|---|---|
| `names` | Set custom column names |
| `header` | Which row (if any) is the header |
| `index_col` | Use a column as the row index |
| `usecols` | Load only specific columns |
| `skiprows` | Skip rows from the top of the file |
| `nrows` | Limit the number of rows read |
| `on_bad_lines` | Skip/warn on malformed rows |
| `dtype` | Force a column's data type |
| `parse_dates` | Parse columns as datetime |
| `converters` | Apply a function to values while reading |
| `chunksize` | Read a huge file in fixed-size chunks |
| `iterator=True` | Pull chunks manually with `.get_chunk()` |
| `sep` / `delimiter` | Set the field separator |
| `na_values` | Custom missing-value markers |
| `encoding` | Set the file's text encoding |
| `comment` | Ignore comment lines |
| `compression` | Read `.gz` / `.zip` / `.bz2` / `.xz` files directly |

...and for writing data back out, `df.to_csv(path, index=False, columns=[...], sep=...)`.